// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  migrations: {
    // Change 'bun' to 'node'
    seed: "node ./prisma/seed.js",
  },
  // Ensure your datasource is pointing to your environment variable
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
